=== deanrobertcook/myLexicon/xml/settings.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT settings (languages, fields)>
	<!ELEMENT languages (target, base, other*)>
		<!ELEMENT target (#PCDATA)>
		<!ELEMENT base (#PCDATA)>
	
	<!-- List languages here, they will be enforced in the XML-->
	<!ELEMENT english (#PCDATA)>
	<!ELEMENT german (#PCDATA)>
				
	<!ELEMENT fields (field*)>
		<!ELEMENT field (type, order, size, english, german)>
		<!ATTLIST field display CDATA "true">
		<!ATTLIST field required CDATA "false">
			<!ELEMENT type (#PCDATA)>
			<!ELEMENT order (#PCDATA)>
			<!ELEMENT size (#PCDATA)>

=== deanrobertcook/myLexicon/xml/settings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE settings SYSTEM "settings.dtd">
<settings>
	<languages>
		<target>german</target>
		<base>english</base>
	</languages>
	<categories>
		<category>
			<name>animal_welfare</name>
			<english>Animal Welfare</english>
			<german>Die Tierschutz</german>
		</category>
		<category>
			<name>alternative_beliefs</name>
			<english>Alternative Beliefs</english>
			<german>Alternative Überzeugungen</german>
		</category>
	</categories>
	<fields>
		<field display="true" required="true">
			<type>english</type>
			<english>English</english>
			<german>Englisch</german>
		</field>
		<field display="true" required="true">
			<type>german</type>
			<english>German</english>
			<german>Deutsch</german>
		</field>
		<field display="true" required="false">
			<type>example</type>
			<english>Example</english>
			<german>Beispiel</german>
		</field>
		<field display="false" required="true">
			<type>part_of_speech</type>
			<english>Part of Speech</english>
			<german>Wortart</german>
		</field>
		<field display="false" required="true">
			<type>article</type>
			<english>Article</english>
			<german>Artikel</german>
		</field>
		<field display="false" required="false">
			<type>plural</type>
			<english>Plural</english>
			<german>Plural</german>
		</field>
		<field display="false" required="false">
			<type>past_participle</type>
			<english>Past Participle</english>
			<german>Partizip Perfekt</german>
		</field>
		<field display="false" required="false">
			<type>past_participle</type>
			<english>Past Participle</english>
			<german>Partizip Perfekt</german>
		</field>
		<field display="false" required="false">
			<type>simple_past</type>
			<english>Simple Past</english>
			<german>Präteritum</german>
		</field>
		<field display="false" required="false">
			<type>auxiliary_verb</type>
			<english>Auxiliary Verb</english>
			<german>Hilfsverb</german>
		</field>
	</fields>
</settings>
