=== deanrobertcook/myLexicon/lexicon/lexicon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT lexicon (category*)>
<!ELEMENT category (name, term*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT term (english, german, example*)>
<!ELEMENT english (#PCDATA)>
<!ELEMENT german (#PCDATA)>
<!ELEMENT example (#PCDATA)>

=== deanrobertcook/myLexicon/lexicon/lexicon.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lexicon SYSTEM "lexicon.dtd">
<lexicon>
  <category>
    <name>Allgemeine Begriffe</name>
    <term>
      <english>&lt;b&gt;trade&lt;/b&gt; sth. for sth.</english>
      <german>etw. gegen etw. &lt;b&gt;eintauschen&lt;/b&gt;</german>
      <example>Sie muss ihre Wertsachen gegen Lebensmittel eintauschen</example>
    </term>
    <term>
      <english>to &lt;b&gt;affect&lt;/b&gt; so/sth.</english>
      <german>jmdn/etw &lt;b&gt;beeinflussen&lt;/b&gt;</german>
      <example/>
    </term>
  </category>
  <category>
    <name>Flickwörter</name>
    <term>
      <english>tomorrow morning</english>
      <german>morgen früh</german>
    </term>
    <term>
      <english>core of the problem</english>
      <german>den Kern des Problems</german>
      <example/>
    </term>
    <term>
      <english>until I can sth., I won't</english>
      <german>bis ich etw. machen kann, werde ich nicht</german>
      <example/>
    </term>
    <term>
      <english>have you ever been...</english>
      <german>warst du jemals/schon (ein)mal ...</german>
      <example>Warst du schon mal in Zurich gewesen?</example>
    </term>
    <term>
      <english>Have you ever tried ...</english>
      <german>Hast du jemals/schon (ein)mal etw. versucht</german>
      <example/>
    </term>
    <term>
      <english>on second thought</english>
      <german>bei näherem Nachdenken</german>
      <example/>
    </term>
    <term>
      <english>to stumble upon sth. by &lt;b&gt;accident&lt;/b&gt;</english>
      <german>&lt;b&gt;zufällig&lt;/b&gt; auf etw. stoßen</german>
      <example/>
    </term>
    <term>
      <english>just so you know</english>
      <german>nur damit du weißt</german>
      <example/>
    </term>
    <term>
      <english>just out of curiosity</english>
      <german>nur so aus Neugierde</german>
      <example/>
    </term>
  </category>
  <category>
    <name>Alternative Beliefs</name>
  </category>
  <category>
    <name>Animal Welfare</name>
  </category>
  <category>
    <name>Architecture</name>
  </category>
  <category>
    <name>Arts</name>
  </category>
  <category>
    <name>Anatomy</name>
  </category>
  <category>
    <name>Crime and Punishment</name>
  </category>
  <category>
    <name>Cultural Differences</name>
  </category>
  <category>
    <name>Dating</name>
  </category>
  <category>
    <name>Drugs</name>
  </category>
  <category>
    <name>Economics</name>
  </category>
  <category>
    <name>Education</name>
  </category>
  <category>
    <name>Emotion</name>
  </category>
  <category>
    <name>Entertainment</name>
  </category>
  <category>
    <name>Environment</name>
  </category>
  <category>
    <name>Fashion and Clothing</name>
  </category>
  <category>
    <name>Sleep</name>
    <term>
      <english>I'm almost asleep</english>
      <german>Ich schlafe schon fast</german>
      <example/>
    </term>
  </category>
  <category>
    <name>Sprache</name>
    <term>
      <english>correction</english>
      <german>die Korrektur-en</german>
      <example>Danke auch für die Korrektur</example>
    </term>
  </category>
</lexicon>
